name: load-forecasts
channels:
  - conda-forge
dependencies:
  - dask[complete]
  - holoviews
  - hvplot
  - jupyterlab
  - notebook
  - pandas
  - panel
  - scikit-learn
  - diskcache
  - requests
  - pyarrow
  - openpyxl
  - jupyter_bokeh # needed to make panel work in vs code
  - datashader
  - scikit-learn
  - pylint
  - mypy
  - pytest
  - isort
  - black
  - autoflake